name: Ape tests

on:
  push:
    branches:
    - master
  pull_request:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        tokens_to_test: [6, 8, 18, usdt]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        python-version: '3.10'

    - name: install requirements
      run: python3 -m pip install -r requirements.txt 
    
    - name: install plugins
      run: ape plugins install .
    
    - name: Compile contracts
      # TODO: Force recompiles until ape compile caching is fixed
      run: ape compile --force --size

    # Needed to use hardhat
    - name: Setup node.js
      uses: actions/setup-node@v1
      with:
        node-version: '18.x'

    - name: Install hardhat
      run: npm install hardhat

    - name: output current installation
      run: pip freeze

    - name: Run tests
      run: ape test -s
      timeout-minutes: 15
      env:
        TOKENS_TO_TEST: ${{ matrix.tokens_to_test }}
